#!/bin/bash

## Install build dependencies.
sudo apt install git debhelper build-essential

## Build and install the package.
git clone https://github.com/firdavis/tor-control-panel.git
cd tor-control-panel
dpkg-buildpackage -b
cd -
ls tor-control-panel*.deb > package-version
sudo apt install -y ./$(cat package-version)

## Run tor-control-panel which will complete
## it's own congiguration.
tor-control-panel
